export const TokenLegend = {
    jass_comment: 0,
    jass_type: 1,
    jass_function: 2,
    jass_function_native: 3,
    jass_argument: 4,
    jass_comma: 5,
    jass_variable: 6,
    jass_operator: 7,
    jass_type_keyword: 8,
    jass_local_keyword: 9,
    jass_extends_keyword: 10,
    jass_constant_keyword: 11,
    jass_native_keyword: 12,
    jass_function_keyword: 13,
    jass_endfunction_keyword: 14,
    jass_takes_keyword: 15,
    jass_returns_keyword: 16,
}
export const TokenLegendList = ['jass_comment', 'jass_type', 'jass_function', 'jass_function_native', 'jass_argument', 'jass_comma', 'jass_variable', 'jass_operator', 'jass_type_keyword', 'jass_local_keyword', 'jass_extends_keyword', 'jass_constant_keyword', 'jass_native_keyword', 'jass_function_keyword', 'jass_endfunction_keyword', 'jass_takes_keyword', 'jass_returns_keyword']